### ISSUE TITLE
Projetos Open-Source referências

### ISSUE THREAD

**Issue by rennanoliveira** [felipeorlando/aprenda-rubyonrails#17]
Existe o interesse de listar também projetos open-source que são boas referências de código? (Não apenas gems, projetos inteiros)

Eles também são uma excelente fonte de aprendizado.
Ex: [Catarse](https://github.com/catarse/catarse), [Discourse](https://github.com/discourse/discourse)

**Comment by felipeorlando** [comment]
@rennanoliveira A ideia é bacana. Se quiser, pode fazer um pull-request no repo. Inclusive, aqui lista alguns: www.opensourcerails.com :smile:

**Comment by rennanoliveira** [comment]
Pode ser mais interessante, talvez, listar repositórios/links que agreguem conteúdos de rails, tipo:
Página com projetos open source em rails: <Link>
repositório com coletâneas de postagens de rails: <Link>

O que acham mais interessante?
A idéia seria aproveitar o que a comunidade já organizou

**Comment by felipeorlando** [comment]
Eu e o @evansantos estamos pensando em tronar o ROR:R em algo mais universal e organizado que o atual. Primeiramente, separemos cada sessão em partes, passaremos-o para inglês (mantendo foco no conteúdo pt-BR) e faremos algumas pequenas mudanças de forma geral. Então aguarde uma PORRADA de novidades. :smiley::+1:

**Comment by felipeorlando** [comment]
Depois de muito tempo, irei voltar a manter este repositótio. Espero melhorar algumas coisas e colocar em pauta outras pendentes. :smiley:
