### ISSUE TITLE
Cursos do Udacity

### ISSUE THREAD

**Issue by rodrigobaron** [felipeorlando/aprenda-rubyonrails#21]
Estou aguardando dois cursos do Udacity:
- [Ruby on Rails Developer](https://www.udacity.com/course/ruby-on-rails-developer--nd020)
- [Senior Ruby on Rails Developer](https://www.udacity.com/course/senior-ruby-on-rails-developer--nd030)

não sei se tem interesse de colocar algo _coming-soon_.

**Comment by evansantos** [comment]
@rodrigobaron esses são interessantes... eu vi hoje eles são nano degrees, não? 

@felipeorlando compensa criar uma área como nano degrees/degrees?

**Comment by felipeorlando** [comment]
Ao que me parece, os programas de nanodegree do Udacity não contam mais Ruby/Rails em suas ementas.

Além disso, nanodegree ainda não está assim tão padronizado, ao meu ver. O Treehouse mesmo tem algo extremamente parecido, chamado Techdegree... então, é complicado identificar o que é certo e o que é errado...

**Comment by evansantos** [comment]
@felipe nano/tech são as mesmas coisas só muda o conceito por causa do nome
